"""Add is_active to offers

Revision ID: 46516f2afe07
Revises: d0eaca9d68f0
Create Date: 2025-08-01 18:29:22.665049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46516f2afe07'
down_revision: Union[str, Sequence[str], None] = 'd0eaca9d68f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'is_active')
    # ### end Alembic commands ###
