"""Add favorites table

Revision ID: 76706438684c
Revises: 46516f2afe07
Create Date: 2025-08-04 12:50:26.113572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76706438684c'
down_revision: Union[str, Sequence[str], None] = '46516f2afe07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_offer_uc', 'favorites', ['user_id', 'offer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_offer_uc', 'favorites', type_='unique')
    # ### end Alembic commands ###
